import "./globals.css";
import Header from "@/components/Header";
import StoreProvider from "@/components/StoreProvider";

export const metadata = {
  title: "Option Desk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-black dark:text-white">
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
